version: "3.1"

services:
  web:
    image: ${DTR_URL}/admin/hello-world-python:${TAG}
    ports:
     - "5000"
    networks:
      - hello-world
    labels:
      - "com.docker.ucp.access.label=/demo-collection/${ENVIRONMENT}"
      - "interlock.hostname=hello-world-${ENVIRONMENT}"
      - "interlock.domain=${DOMAIN_NAME}"
    

  redis:
    image: redis:3.2-alpine
    command: redis-server --appendonly yes
    networks:
      - hello-world
    volumes:
      - redis-data:/data
    labels:
      - "com.docker.ucp.access.label=/demo-collection/${ENVIRONMENT}"
   

networks:
  hello-world:
   labels:
      - "com.docker.ucp.access.label=/demo-collection/${ENVIRONMENT}"
    

volumes:
  redis-data:
    driver: local
    labels:
      - "com.docker.ucp.access.label=/demo-collection/${ENVIRONMENT}"
